# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_transfers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfers',
            new_name='Transfers_List',
        ),
    ]
