# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190511_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers_list',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='transfers_list',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
